//
//  DashboardInteractorTests.swift
//  CuteFondMemories
//
//  Created by Maryam Chrs on 21/02/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CuteFondMemories
import XCTest

class DashboardInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: DashboardInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupDashboardInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupDashboardInteractor()
  {
    sut = DashboardInteractor()
  }
  
  // MARK: Test doubles
  
  class DashboardPresentationLogicSpy: DashboardPresentationLogic
  {
    var presentSomethingCalled = false
    
    func presentSomething(response: Dashboard.Something.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = DashboardPresentationLogicSpy()
    sut.presenter = spy
    let request = Dashboard.Something.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
